substitutions:
  devicename: "idslorareceiver"
  friendly_name: "IDS Lora receiver"

esphome:
  name: $devicename
  build_path: build/$devicename
  platform: ESP32
  board: heltec_wifi_lora_32_V2
  includes:
    - src/custom_ids_lora_receiver/custom_ids_lora_receiver.h
    - src/custom_ids_lora_receiver/images.h
    - src/custom_ids_lora_receiver/myoleddisplay.h
    - src/custom_ids_lora_receiver/structures.h
    - src/custom_ids_lora_receiver/myoleddisplay.cpp
  libraries:
    - "LoRa"
    - "ESP8266_SSD1306"

wifi: !include "common/wifi.yaml"
captive_portal:
logger:
api:
ota:

sensor:
- platform: custom
  lambda: |-
    auto ids_lora_receiver = new IDSLoraReceiver();
    App.register_component(ids_lora_receiver);
    return {
      ids_lora_receiver->ids_device_batt_voltage,
      ids_lora_receiver->ids_device_batt_percent,
      ids_lora_receiver->ids_device_batt_islow,
      ids_lora_receiver->ids_device_pir_state,
      ids_lora_receiver->ids_device_alarm_isactive
    };
  sensors:
  - name: "IDS battery voltage"
    accuracy_decimals: 1
    icon: mdi:battery
    unit_of_measurement: v
  - name: "IDS battery percentage"
    accuracy_decimals: 1
    icon: mdi:percent
    unit_of_measurement: '%'
  - name: "IDS battery is low"
    accuracy_decimals: 0
    icon: mdi:battery
  - name: "IDS PIR state"
    accuracy_decimals: 0
    icon: mdi:eye
  - name: "IDS Alarm is active"
    accuracy_decimals: 0
    icon: mdi:bell

