substitutions:
  devicename: "testrfid"
  friendly_name: "Rfid tag reader test"

esphome:
  name: $devicename
  build_path: build/$devicename
  platform: ESP32
  board: esp32doit-devkit-v1

wifi: !include "common/wifi.yaml"
captive_portal:
logger:
api:
ota:

spi:
  clk_pin: 25
  miso_pin: 26
  mosi_pin: 27

pn532:
  cs_pin: 14
  update_interval: 1s
  on_tag:
    then:
    - homeassistant.tag_scanned: !lambda 'return x;'

binary_sensor:
  - platform: status
    name: "$friendly_name Status"

switch:
  - platform: restart
    name: "$friendly_name Restart"

sensor:
  - platform: wifi_signal
    name: "$friendly_name WiFi Signal"
    update_interval: 10s
  - platform: "uptime"
    name: "$friendly_name Uptime"
