substitutions:
  devicename: "testwatch"
  friendly_name: "Test TTGO TWatch"

esphome:
  name: $devicename
  build_path: build/$devicename
  platform: ESP32
  board: ttgo-t-watch
  includes:
    - "src/custom_watch/custom_watch.h"
  libraries:
    - "https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library"
    - "https://github.com/earlephilhower/ESP8266Audio"
    - "https://github.com/earlephilhower/ESP8266SAM"

wifi: !include "common/wifi.yaml"
captive_portal:
logger:
api:
ota:

custom_component:
  - lambda: |-
      auto custom_twatch = new TWatch();
      return {custom_twatch};

binary_sensor:
  - platform: status
    name: "$friendly_name Status"

switch:
  - platform: restart
    name: "$friendly_name Restart"

sensor:
  - platform: wifi_signal
    name: "$friendly_name WiFi Signal"
    update_interval: 10s
  - platform: "uptime"
    name: "$friendly_name Uptime"