substitutions:
  devicename: "zillocube"
  friendly_name: "ZilloCube"

esphome:
  name: $devicename
  build_path: build/$devicename
  platform: ESP32
  board: esp32doit-devkit-v1
  on_boot:
    - priority: 1000
      then:
        - lambda: |-
            fastled_base_fastledlightoutput->get_controller()->setDither(0);
    - priority: 600
      then:
        - light.turn_on:
            id: leds
            brightness: 1
            effect: Boot
    - priority: 0
      then:
        - light.turn_on:
            id: leds
            brightness: 1
            effect: Rainbow

wifi: !include "common/wifimulti.yaml"
ota:
logger:

api:
  services:
    - service: notification
      variables:
        effect: string
        timeout: int
      then:
        - light.turn_on:
            id: leds
            brightness: 1
            effect: !lambda 'return effect;'
        - delay: !lambda 'return timeout*1000;'
        - light.turn_on:
              id: leds
              brightness: 1
              effect: Rainbow

binary_sensor:
  - <<: !include "common/common_binary_sensors.yaml"

switch:
  - <<: !include "common/common_switchs.yaml"

sensor:
  - <<: !include "common/common_sensors.yaml"

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO25
    num_leds: 17
    rgb_order: GRB
    id: leds
    name: "$friendly_name Leds"
    #color_correct: [60%, 60%, 60%]
    default_transition_length: 0s
    restore_mode: ALWAYS_OFF
    effects:
      - lambda:
          name: Boot
          update_interval: 100ms
          lambda: |-
            static int state = 0;
            if (state == 0) {
              auto call = id(leds).turn_on();
              call.set_transition_length(100);
              call.set_rgb(1.0, 1.0, 1.0);
              call.perform();
              state=1;
            } else {
              auto call = id(leds).turn_off();
              call.set_transition_length(100);
              call.set_rgb(1.0, 1.0, 1.0);
              call.perform();
              state=0;
            }
      - addressable_rainbow:
          name: Rainbow
          width: 512
          speed: 1
      - strobe:
          name: BlinkBlue
          colors:
            - state: True
              brightness: 100%
              red: 0%
              green: 20%
              blue: 90%
              duration: 500ms
            - state: False
              duration: 250ms
      - strobe:
          name: FlashBlue
          colors:
            - state: True
              brightness: 100%
              red: 20%
              green: 60%
              blue: 90%
              duration: 300ms
            - state: False
              duration: 250ms
