substitutions:
  devicename: "zillodevkit"
  friendly_name: "Zillo Devkit"

esphome:
  name: $devicename
  platform: ESP32
  board: esp32doit-devkit-v1

wifi: !include "common/wifi.yaml"
captive_portal:
logger:
api:
ota:

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO27
    num_leds: 64
    rgb_order: GRB
    name: "$friendly_name Matrix"
    effects:
      - strobe:
          name: Strobe police
          colors:
            - state: True
              brightness: 50%
              red: 100%
              green: 0%
              blue: 0%
              duration: 10ms
            - state: False
              duration: 5ms
            - state: True
              brightness: 50%
              red: 0%
              green: 0%
              blue: 100%
              duration: 10ms
      - strobe:
          name: notification charge complete
          colors:
            - state: True
              brightness: 30%
              red: 100%
              green: 100%
              blue: 0%
              duration: 1000ms
            - state: False
              duration: 750ms
      - addressable_color_wipe:
          name: Color Wipe Effect With Custom Values
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 1
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 1
          add_led_interval: 100ms
          reverse: False