substitutions:
  devicename: "zilloscope"
  friendly_name: "Zilloscope"

esphome:
  name: $devicename
  build_path: build/$devicename
  platform: ESP32
  board: esp32doit-devkit-v1

  on_boot:
    - priority: 1000
      then:
        - lambda: |-
            fastled_base_fastledlightoutput->get_controller()->setDither(0);
    - priority: -10
      then:
        - switch.turn_on: zilloscope_control_display
    - priority: 0
      then:
        - lambda: |-
            id(zilloscope_main).on_boot();

  on_shutdown:
    then:
      - lambda: |-
          id(zilloscope_main).on_shutdown();


wifi: !include "common/wifi.yaml"
captive_portal:
logger:
api:
ota:

binary_sensor:
  - <<: !include "common/common_binary_sensors.yaml"

switch:
  - <<: !include "common/common_switchs.yaml"
  - platform: template
    id: zilloscope_control_display
    name: "${friendly_name} Control Display"
    turn_on_action:
      - lambda: |-
          id(zilloscope_display).set_enabled(true);
    turn_off_action:
      - lambda: |-
          id(zilloscope_display).set_enabled(false);

sensor:
  - <<: !include "common/common_sensors.yaml"

text_sensor:
  - platform: homeassistant
    id: extratext
    entity_id: input_text.zilloscope_text

font:
  - id: tinyfont
    file: "fonts/pixelmix.ttf"
    size: 8
    glyphs: '♡Ωäöüß!"%()+,-_.:*=°?~#0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz'

time:
  - platform: homeassistant
    id: homeassistant_time

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO5
    num_leds: 256
    rgb_order: GRB
    name: "$friendly_name Matrix"
    id: zilloscope_matrix
    color_correct: [50%, 50%, 50%]
    default_transition_length : 0s
    #gamma_correct: 0
    restore_mode : ALWAYS_ON

animation:
  - file: "img/zillo/zilloscope1.gif"
    id: my_animation
    type: RGB24
    resize: 32x8

display:
  - platform: addressable_light_display
    id: zilloscope_display
    addressable_light_id: zilloscope_matrix
    width: 32
    height: 8
    update_interval: 16ms
    lambda: |-
      id(zilloscope_main).display_lambdacall(it);
    pixel_mapper: |-
      if (x % 2 == 0) {
        return (x * 8) + y;
      }
      return (x * 8) + (7 - y);

zilloscope:
  id: zilloscope_main
  display_id: zilloscope_display
  font_id: tinyfont
  time_id: homeassistant_time

  render_boot: |-

    //go next frame
    id(my_animation).next_frame();

    // Draw the animation at position [x=0,y=0]
    id(zilloscope_display).image(0, 0, id(my_animation));

  render_time: |-
    //TODO use text center
    it.strftime(5, -1, id(tinyfont),  Color(0xFFFFFF), ((millis()/1000)%2==0)?"%H:%M":"%H:%M.", id(homeassistant_time).now());

  render_ota: |-
    it.print(0, 0, id(tinyfont), Color(0x0000FF), "OTA");

  render_shutdown: |-
    it.print(0, 0, id(tinyfont), Color(0xFF0000), "STOP");