substitutions:
  devicename: "zillodevkit"
  friendly_name: "Zillo Devkit"

esphome:
  name: $devicename
  build_path: build/$devicename
  platform: ESP32
  board: esp32doit-devkit-v1
  includes:
    - "src/custom_zillodevkit/effect_zillofeu.h"
  on_boot:
    - priority: 1000
      then:
        - lambda: |-
            fastled_base_fastledlightoutput->get_controller()->setDither(0);
    - priority: 0
      then:
        - light.turn_on:
            id: ledmatrix
            brightness: 1
            effect: Rainbow

wifi: !include "common/wifimulti.yaml"
logger:
api:
ota:

binary_sensor:
  - <<: !include "common/common_binary_sensors.yaml"

switch:
  - <<: !include "common/common_switchs.yaml"

sensor:
  - <<: !include "common/common_sensors.yaml"

e131:
  method: multicast

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO27
    num_leds: 64
    rgb_order: GRB
    id: ledmatrix
    name: "$friendly_name Matrix"
    gamma_correct: 0
    color_correct: [60%, 60%, 60%]
    effects:
      - e131:
          name: Stream
          universe: 1
          channels: RGB
      - addressable_lambda:
          name: "Fire2012"
          update_interval: 16ms
          lambda: |-
            static byte heat[64];

            // Step 1.  Cool down every cell a little
            for( int i = 0; i < 64; i++) {
              heat[i] = qsub8( heat[i],  random8(0, ((COOLING * 10) / 64) + 2));
            }
            // Step 2.  Heat from each cell drifts 'up' and diffuses a little
            for( int k= 64 - 1; k >= 2; k--) {
              heat[k] = (heat[k - 1] + heat[k - 2] + heat[k - 2] ) / 3;
            }
            // Step 3.  Randomly ignite new 'sparks' of heat near the bottom
            if( random8() < SPARKING ) {
              int y = random8(7);
              heat[y] = qadd8( heat[y], random8(160,255) );
            }
            // Step 4.  Map from heat cells to LED colors
            for( int j = 0; j < 64; j++) {
              CRGB color = HeatColor( heat[j]);
              int pixelnumber;
              if( gReverseDirection ) {
                pixelnumber = (64-1) - j;
              } else {
                pixelnumber = j;
              }
              it[pixelnumber] = ESPColor(color.red, color.green, color.blue);
            }
      - addressable_color_wipe:
          name: Wipe
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 64
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 64
          add_led_interval: 100ms
          reverse: False
      - addressable_rainbow:
          name: Rainbow
      - strobe:
          name: Strobe police
          colors:
            - state: True
              brightness: 50%
              red: 100%
              green: 0%
              blue: 0%
              duration: 30ms
            - state: False
              duration: 15ms
            - state: True
              brightness: 50%
              red: 0%
              green: 0%
              blue: 100%
              duration: 30ms
      - strobe:
          name: notification charge complete
          colors:
            - state: True
              brightness: 30%
              red: 100%
              green: 100%
              blue: 0%
              duration: 1000ms
            - state: False
              duration: 750ms
